server:
  port: 1200
  servlet:
    context-path: "/tasty-town"

spring:
  application:
    name: Tasty Town Backend

  datasource:
    url: jdbc:postgresql://localhost/sb_oct
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#ROOT LEVEL LOGGING
logging:
  level:
    root: INFO


upload:
  image:
    path: images
