

spring:
  application:
    name: Tasty Town Backend

  datasource:
    url: jdbc:postgresql://localhost/sb_oct
    username: postgres
    password: lion

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true



# Root level logging
logging:
  level:
    root: INFO
