spring:
  application:
    name: methods-of-jpa

  datasource:
    url: jdbc:mysql://localhost/sb_oct
    username: root
    password: tiger

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true